export const restaurantesTypes = {
  RESTAURANTES_GET: "RESTAURANTES_GET",
  RESTAURANTES_ADD: "RESTAURANTES_ADD",
  RESTAURANTES_FILTERED: "RESTAURANTES_FILTERED",
  RESTAURANT_SINGLE_GET: "RESTAURANTES_SINGLE_GET",
  RESTAURANT_DELETE: "RESTAURANTES_DELETE",
};
export const foodTypes = {
  FOOD_GET: "FOOD_GET",
  FOOD_FILTERED: "FOOD_FILTERED",
  FOOD_ADD: "FOOD_ADD",
  FOOD_DELETE: "FOOD_DELETE",
};
export const ordenTypes = {
  ORDEN_GET: "ORDEN_GET",
  ORDEN_ADD: "ORDEN_ADD",
};
