export const restaurantesTypes = {
  RESTAURANTES_GET: "RESTAURANTES_GET",
  RESTAURANTES_ADD: "RESTAURANTES_ADD",
  RESTAURANTES_FILTERED: "RESTAURANTES_FILTERED",
  RESTAURANT_SINGLE_GET: "RESTAURANT_SINGLE_GET",
};
